# Playing with matrices
(and if you get the subliminal message about abstractions, we'll be thrilled!)

Julia is a dynamic language.  You don't need type declarations, and can change variable types dynamically and interactively.

For working with simple numbers, arrays, and strings, its syntax is *superficially* similar to Matlab, Python, and other popular languages.

In order to execute the "In" cells, select the cell and press Shift-Enter, or press the Play button above. To run the entire notebook, navigate to Cell and then click Run All.

# We tell beginners, you don't need types!

In [49]:
typeof(1.0)

Float64

In [50]:
typeof(1)

Int64

In [51]:
S = "Hello Julia Clsas"
typeof(S)

String

In [52]:
#  Exercise fix my spelling in the cell above
S

"Hello Julia Clsas"

# Now forget all that (for now): Julia is not so different from your favorite dynamic language

In [54]:
1+1 # shift + enter

2

In [55]:
A = rand(5,5)

5×5 Array{Float64,2}:
 0.0905692  0.774974  0.611401  0.146823   0.0806722
 0.479015   0.281654  0.674683  0.312236   0.0266526
 0.226797   0.843853  0.567345  0.0360118  0.628536 
 0.428604   0.285277  0.119579  0.83066    0.217538 
 0.193814   0.55981   0.64561   0.750543   0.922337 

In [56]:
A = SymTridiagonal(rand(6),rand(5))

6×6 SymTridiagonal{Float64}:
 0.745379  0.125671   ⋅         ⋅         ⋅         ⋅      
 0.125671  0.615728  0.975613   ⋅         ⋅         ⋅      
  ⋅        0.975613  0.388808  0.207589   ⋅         ⋅      
  ⋅         ⋅        0.207589  0.864522  0.876492   ⋅      
  ⋅         ⋅         ⋅        0.876492  0.266047  0.186814
  ⋅         ⋅         ⋅         ⋅        0.186814  0.598772

In [57]:
b = rand(6)
A\b

6-element Array{Float64,1}:
 -0.048587 
  1.06903  
 -0.578116 
 -0.0972513
  1.02916  
  1.10864  

In [58]:
A = fill(3.15,5,5) # Fill a 5x5 array with 0's

5×5 Array{Float64,2}:
 3.15  3.15  3.15  3.15  3.15
 3.15  3.15  3.15  3.15  3.15
 3.15  3.15  3.15  3.15  3.15
 3.15  3.15  3.15  3.15  3.15
 3.15  3.15  3.15  3.15  3.15

In [59]:
# Exercise: Fill a 3x10 array with 7's
A = rand(5, 5)

5×5 Array{Float64,2}:
 0.879906  0.62004    0.692117  0.796874   0.957766 
 0.845618  0.464479   0.284221  0.238622   0.0370238
 0.645619  0.680148   0.928282  0.464066   0.978996 
 0.68223   0.0725246  0.804269  0.0800176  0.73905  
 0.657212  0.217781   0.885215  0.973917   0.520234 

# Let's create some addition tables

In [60]:
A = zeros(5,5)
# Create an addition table: Nested for loop
for i=1:5
    for j=1:5
        A[i,j] = i+j  # Square brackets for indices.  Also: indices start at 1, not 0.
    end
end

A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [61]:
# Create an addition table: "Double" for loop
for i=1:5, j=1:5
   A[i,j] = i+j  # Square brackets for indices.  Also: indices start at 1, not 0.
end

A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [62]:
# Create an addition table: the Julia favorite way

[i+j for i=1:5, j=1:5]

# Vocabulary word of the day: Comprehension  (other languges use "meshgrid")

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [63]:
# Exercise and explore: What does this do?
[ i*100 for i in (1:7).^2]

# Exercise and explore: Explain this way to find numbers of the form x^2 + y^2 
sort(unique(x^2+y^2 for x in 1:5 ,y in 1:5))  # This is called a generator 

15-element Array{Any,1}:
  2
  5
  8
 10
 13
 17
 18
 20
 25
 26
 29
 32
 34
 41
 50

In [64]:
# Suppose we want to see nxn addition tables for n=1,2,3,4,5
for n=1:5
    display([i*j for i=1:n,j=1:n])
end

1×1 Array{Int64,2}:
 1

2×2 Array{Int64,2}:
 1  2
 2  4

3×3 Array{Int64,2}:
 1  2  3
 2  4  6
 3  6  9

4×4 Array{Int64,2}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

5×5 Array{Int64,2}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

# Interact is a "package" with the `@manipulate` "macro"

In [65]:
# way more fun way to "interact" with data
#Pkg.add("Interact")
using Interact # using loads a "package"

In [66]:
@manipulate for n=1:1000
    n
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(500, nactions=1),"n",500,"500",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…),Dict(306=>"306",29=>"29",74=>"74",905=>"905",176=>"176",892=>"892",285=>"285",318=>"318",873=>"873",975=>"975"…)),Any[],Any[],true,"horizontal")

500

In [67]:
using Interact   # using loads a "package" 
@manipulate for n=1:20
    [i*j for i=1:n,j=1:n]
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(10, nactions=1),"n",10,"10",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…),Dict(18=>"18",2=>"2",16=>"16",11=>"11",7=>"7",9=>"9",10=>"10",19=>"19",17=>"17",8=>"8"…)),Any[],Any[],true,"horizontal")

10×10 Array{Int64,2}:
  1   2   3   4   5   6   7   8   9   10
  2   4   6   8  10  12  14  16  18   20
  3   6   9  12  15  18  21  24  27   30
  4   8  12  16  20  24  28  32  36   40
  5  10  15  20  25  30  35  40  45   50
  6  12  18  24  30  36  42  48  54   60
  7  14  21  28  35  42  49  56  63   70
  8  16  24  32  40  48  56  64  72   80
  9  18  27  36  45  54  63  72  81   90
 10  20  30  40  50  60  70  80  90  100

In [68]:
#double slider!!  Put a 3x3 block of i's in an n x n matrix of zeros
@manipulate for n=3:10, i=1:9
   A = fill(0,n,n)
   A[1:3, 1:3] = i  
A
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(6, nactions=1),"n",6,"6",Interact.OptionDict(DataStructures.OrderedDict("3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10),Dict(7=>"7",4=>"4",9=>"9",10=>"10",3=>"3",5=>"5",8=>"8",6=>"6")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(5, nactions=1),"i",5,"5",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9),Dict(7=>"7",4=>"4",9=>"9",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

6×6 Array{Int64,2}:
 5  5  5  0  0  0
 5  5  5  0  0  0
 5  5  5  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0

# Functions

In [69]:
# verbose form
function f(x)
    x^2
end

# one-line form
f2(x) = x^2

# anonymous form
f3 = x -> x^2;

In [70]:
f(10)

100

In [71]:
f(rand(3,3))

3×3 Array{Float64,2}:
 1.09848  1.54237  0.731099
 1.45039  1.81384  1.16019 
 1.8844   2.19408  1.30413 

In [72]:
function f(x, power=2) # default argument
    x^power
end

f (generic function with 2 methods)

In [73]:
f(7)

49

In [74]:
f(10,3)

1000

In [75]:
function insert_block(A, i, j, what=7)
    B = A[:,:]        # B is a copy of A       
    B[ i:i+2, j:j+2] = fill(what,3,3)
    B
end

insert_block (generic function with 2 methods)

In [76]:
A = fill(0,9,9)
insert_block(A, 3, 5)

9×9 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  7  7  7  0  0
 0  0  0  0  7  7  7  0  0
 0  0  0  0  7  7  7  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0

In [77]:
A = fill(0,9,9)
insert_block(A, 3, 5, 2)  # Use 2 instead of 7

9×9 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  2  2  2  0  0
 0  0  0  0  2  2  2  0  0
 0  0  0  0  2  2  2  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0

In [78]:
A = fill(0,10,10)
n =size(A,1)
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

# Strings

In [79]:
S = "Hello"

"Hello"

In [80]:
replace(S, "H", "J")

"Jello"

In [81]:
string(S," ", S, " ","Julia")

"Hello Hello Julia"

More about strings: <a href="http://docs.julialang.org/en/stable/manual/strings/"> Julia Doc on Strings </a>

In [82]:
A = fill("Julia",5,5)

5×5 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"

In [34]:
# Fancy string printing
function Base.show{T<:String}(io::IO, ::MIME"text/html", M::Matrix{T}) 
    max_length = maximum(length.(M))
    dv="<div style='display:flex;flex-direction:row'>"
    print(io, dv*join([join("<div style='width:40px; text-align:center'>".*M[i,:].*"</div>", " ") for i in 1:size(M, 1)]
            , "</div>$dv")*"</div>")
end

In [35]:
A

5×5 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"

In [83]:
# Remember this ????
A = fill(0,10,10)
n = size(A,1)
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [84]:
A = fill("Julia",10,10)
n = size(A,1)
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j, " [FUN]")
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"   …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"      "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"      "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  " [FUN]"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  " [FUN]"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  " [FUN]"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"      "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"      "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"      "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"      "Julia"  "Julia"  "Julia"  "Julia"

In [85]:
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j, "π")
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "π"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "π"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "π"      …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"

In [86]:
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j, "♡")
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "♡"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "♡"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "♡"      …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"

In [40]:
airplane = "✈"
alien = "👽"
rand( [airplane,alien],5,5)

5×5 Array{String,2}:
 "👽"  "👽"  "✈"  "👽"  "✈"
 "✈"  "👽"  "✈"  "👽"  "✈"
 "👽"  "✈"  "👽"  "✈"  "👽"
 "👽"  "👽"  "✈"  "👽"  "✈"
 "✈"  "👽"  "👽"  "👽"  "👽"

In [41]:
A = fill(airplane,9,9)
n=size(A,1)
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j, alien)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

9×9 Array{String,2}:
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "👽"  "👽"  "👽"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "👽"  "👽"  "👽"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "👽"  "👽"  "👽"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"

# Colors

In [87]:
using  Colors

In [88]:
distinguishable_colors(12)

In [89]:
@manipulate for n = 1:80
    distinguishable_colors(n)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(40, nactions=1),"n",40,"40",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…),Dict(68=>"68",2=>"2",11=>"11",39=>"39",46=>"46",25=>"25",55=>"55",42=>"42",29=>"29",58=>"58"…)),Any[],Any[],true,"horizontal")

In [45]:
colors = distinguishable_colors(100)


In [46]:
# Remember this ????
A = fill(0,10,10)
n = size(A,1)
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j)
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

10×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [90]:
A = fill(colors[1],10,10)
n =size(A,1)
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j,colors[4])
end

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"i",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(4, nactions=1),"j",4,"4",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8),Dict(7=>"7",4=>"4",2=>"2",3=>"3",5=>"5",8=>"8",6=>"6",1=>"1")),Any[],Any[],true,"horizontal")

In [48]:
# Exercise: Create Tetris Pieces, have them fall from the top